const initialState = {
  data: [
    {
      id: 0,
      text: 'Ngắm bình minh Phú Yên',
      text1: 'Phú Yên, Việt Nam',
      img: 'https://mangphuyen.com/wp-content/uploads/2019/06/hai-dang-dai-lanh-1.jpg',
      price: '1.000.000',
      mapaddress: {
        latitude: 13.5232757,
        longitude: 108.1051243,
      },
      marker: {
        latitude: 13.549059,
        longitude: 108.125472,
      },
      introduce1: require('./../img/vinh68.png'),
      introduce2: require('./../img/vinh69.png'),
      introduce3: require('./../img/vinh70.png'),
      content1: 'Di chuyển từ Đảo lớn sang Đảo bé',
      label1: 'Để di chuyển từ Đảo Lớn sang Đảo Bé du khách sẽ di chuyển bằng Ca Nô. Mỗi lượt vé ca nô khứ hồi hiện nay dành cho du khách là 80k/du khách/khứ hồi.',
      label2: 'Bảng giá thuê ca nô nguyên chiếc khứ hồi:',
      label3: '- Ca nô 25 chỗ: 1600k',
      label4: '- Ca nô 35 chỗ: 2600k.',
      label5: '- Ca nô 40 chỗ: 3100k.',
      content2: 'Thời điểm thích hợp để khám phá Đảo Bé Lý Sơn.',
      label6: ' - Nếu đi Đảo Bé trong ngày, du khách nên xuất phát từ Đảo Lớn lúc sáng sau đó chiều về lại. Du khách ở lại Đảo Bé một ngày thì nên xuất phát từ sáng và về lại lúc trưa ngày hôm sau.',
      label7: ' - Nếu đi Đảo Bé trong ngày, du khách nên xuất phát từ Đảo Lớn lúc sáng sau đó chiều về lại. Du khách ở lại Đảo Bé một ngày thì nên xuất phát từ sáng và về lại lúc trưa ngày hôm sau.',
      content3: 'Chơi gì ở Đảo Bé?',
      text1: 'Lặn ngắm san hô.',
      label8: ' Rạn san hô ở Đảo Bé được đánh giá đẹp nhất Việt Nam. Du khách có thể lựa chọn thuê thuyền thúng đi lặn san hô. Mỗi lần lặn san hô như vậy là giá 80k/người. Giá lặn san hô đã bao gồm tiền thuê kính, thuê áo phao.',
      text2: 'Tắm biển ở Đảo Bé.',
      label9: 'Bãi Sau là bãi tắm nổi tiếng nhất tại Lý Sơn. Ở bãi tắm có nhiều bãi đá đen trầm tích để du khách có thể check-in với những tấm ảnh ấn tượng. Ở Bãi Sau sóng biển khá là bình yên nên việc tắm biển rất thích thú.',
      text3: 'Check-in cây cô đơn và cầu sống ảo.',
      label10: 'Cây phong ba dù đứng một mình ở Bãi Tây vẫn được cư dân mạng phong tặng là cây cô đơn ở Lý Sơn. Cây có hình dáng lạ, đẹp được nhiều du khách ưu thích check-in. Ngoài cây cô đơn trên Đảo Bé còn có cây cầu sống ảo du khách không thể bỏ qua.',
      text4: 'Ở lại homestay tại Đảo Bé.',
      label11: 'So với các homestay trên Đảo Lớn thì hiện tại ở Đảo Bé có rất nhiều homestay giúp du khách có thể gần gũi với thiên nhiên. Buổi tối bạn có muốn tổ chức một buổi tiệc BBQ trên biển thật sự hay căm trại tại Đảo Bé. Đây sẽ là những trải nghiệm mà không phải ai cũng có thể có được khi đến Lý Sơn.',
      offer: [
        { img1: require('./../img/vinh71.png'), textimg1: 'Thắng cảnh Hòn Đụn', },
        { img1: require('./../img/vinh72.png'), textimg1: 'Núi Thới Lới', },
        { img1: require('./../img/vinh73.png'), textimg1: 'Phú Quốc, Kiên Giang', },
      ]

    },
    {
      id: 1,
      text: 'Chinh phục Fanxipan',
      text1: 'Lào Cai, Việt Nam',
      img: 'https://thesuntourist.com/wp-content/uploads/2019/05/1548127579_chinh-phuc-dinh-fansifan-1.jpg',
      price: '8000.000',
      mapaddress: {
        latitude: 13.5232757,
        longitude: 108.1051243,
      },
      marker: {
        latitude: 13.118198,
        longitude: 108.852250,
      },
      introduce1: require('./../img/vinh68.png'),
      introduce2: require('./../img/vinh69.png'),
      introduce3: require('./../img/vinh70.png'),
      content1: 'Di chuyển từ Đảo lớn sang Đảo bé',
      label1: 'Để di chuyển từ Đảo Lớn sang Đảo Bé du khách sẽ di chuyển bằng Ca Nô. Mỗi lượt vé ca nô khứ hồi hiện nay dành cho du khách là 80k/du khách/khứ hồi.',
      label2: 'Bảng giá thuê ca nô nguyên chiếc khứ hồi:',
      label3: '- Ca nô 25 chỗ: 1600k',
      label4: '- Ca nô 35 chỗ: 2600k.',
      label5: '- Ca nô 40 chỗ: 3100k.',
      content2: 'Thời điểm thích hợp để khám phá Đảo Bé Lý Sơn.',
      label6: ' - Nếu đi Đảo Bé trong ngày, du khách nên xuất phát từ Đảo Lớn lúc sáng sau đó chiều về lại. Du khách ở lại Đảo Bé một ngày thì nên xuất phát từ sáng và về lại lúc trưa ngày hôm sau.',
      label7: ' - Nếu đi Đảo Bé trong ngày, du khách nên xuất phát từ Đảo Lớn lúc sáng sau đó chiều về lại. Du khách ở lại Đảo Bé một ngày thì nên xuất phát từ sáng và về lại lúc trưa ngày hôm sau.',
      content3: 'Chơi gì ở Đảo Bé?',
      text1: 'Lặn ngắm san hô.',
      label8: ' Rạn san hô ở Đảo Bé được đánh giá đẹp nhất Việt Nam. Du khách có thể lựa chọn thuê thuyền thúng đi lặn san hô. Mỗi lần lặn san hô như vậy là giá 80k/người. Giá lặn san hô đã bao gồm tiền thuê kính, thuê áo phao.',
      text2: 'Tắm biển ở Đảo Bé.',
      label9: 'Bãi Sau là bãi tắm nổi tiếng nhất tại Lý Sơn. Ở bãi tắm có nhiều bãi đá đen trầm tích để du khách có thể check-in với những tấm ảnh ấn tượng. Ở Bãi Sau sóng biển khá là bình yên nên việc tắm biển rất thích thú.',
      text3: 'Check-in cây cô đơn và cầu sống ảo.',
      label10: 'Cây phong ba dù đứng một mình ở Bãi Tây vẫn được cư dân mạng phong tặng là cây cô đơn ở Lý Sơn. Cây có hình dáng lạ, đẹp được nhiều du khách ưu thích check-in. Ngoài cây cô đơn trên Đảo Bé còn có cây cầu sống ảo du khách không thể bỏ qua.',
      text4: 'Ở lại homestay tại Đảo Bé.',
      label11: 'So với các homestay trên Đảo Lớn thì hiện tại ở Đảo Bé có rất nhiều homestay giúp du khách có thể gần gũi với thiên nhiên. Buổi tối bạn có muốn tổ chức một buổi tiệc BBQ trên biển thật sự hay căm trại tại Đảo Bé. Đây sẽ là những trải nghiệm mà không phải ai cũng có thể có được khi đến Lý Sơn.',
      offer: [
        { img1: require('./../img/vinh71.png'), textimg1: 'Thắng cảnh Hòn Đụn', },
        { img1: require('./../img/vinh72.png'), textimg1: 'Núi Thới Lới', },
        { img1: require('./../img/vinh73.png'), textimg1: 'Phú Quốc, Kiên Giang', },
      ]
    },
    {
      id: 2,
      text: 'Trải Nghiệm là người dân bản',
      text1: 'SaPa, Việt Nam',
      img: 'https://www.chudu24.com/wp-content/uploads/2020/07/anhthuy1202-192222032254-du-lich-sapa-ban-cat-cat.jpg',
      price: '1.500.000',
      mapaddress: {
        latitude: 13.5232757,
        longitude: 108.1051243,
      },
      marker: {
        latitude: 13.118198,
        longitude: 108.852250,
      },
      introduce1: require('./../img/vinh68.png'),
      introduce2: require('./../img/vinh69.png'),
      introduce3: require('./../img/vinh70.png'),
      content1: 'Di chuyển từ Đảo lớn sang Đảo bé',
      label1: 'Để di chuyển từ Đảo Lớn sang Đảo Bé du khách sẽ di chuyển bằng Ca Nô. Mỗi lượt vé ca nô khứ hồi hiện nay dành cho du khách là 80k/du khách/khứ hồi.',
      label2: 'Bảng giá thuê ca nô nguyên chiếc khứ hồi:',
      label3: '- Ca nô 25 chỗ: 1600k',
      label4: '- Ca nô 35 chỗ: 2600k.',
      label5: '- Ca nô 40 chỗ: 3100k.',
      content2: 'Thời điểm thích hợp để khám phá Đảo Bé Lý Sơn.',
      label6: ' - Nếu đi Đảo Bé trong ngày, du khách nên xuất phát từ Đảo Lớn lúc sáng sau đó chiều về lại. Du khách ở lại Đảo Bé một ngày thì nên xuất phát từ sáng và về lại lúc trưa ngày hôm sau.',
      label7: ' - Nếu đi Đảo Bé trong ngày, du khách nên xuất phát từ Đảo Lớn lúc sáng sau đó chiều về lại. Du khách ở lại Đảo Bé một ngày thì nên xuất phát từ sáng và về lại lúc trưa ngày hôm sau.',
      content3: 'Chơi gì ở Đảo Bé?',
      text1: 'Lặn ngắm san hô.',
      label8: ' Rạn san hô ở Đảo Bé được đánh giá đẹp nhất Việt Nam. Du khách có thể lựa chọn thuê thuyền thúng đi lặn san hô. Mỗi lần lặn san hô như vậy là giá 80k/người. Giá lặn san hô đã bao gồm tiền thuê kính, thuê áo phao.',
      text2: 'Tắm biển ở Đảo Bé.',
      label9: 'Bãi Sau là bãi tắm nổi tiếng nhất tại Lý Sơn. Ở bãi tắm có nhiều bãi đá đen trầm tích để du khách có thể check-in với những tấm ảnh ấn tượng. Ở Bãi Sau sóng biển khá là bình yên nên việc tắm biển rất thích thú.',
      text3: 'Check-in cây cô đơn và cầu sống ảo.',
      label10: 'Cây phong ba dù đứng một mình ở Bãi Tây vẫn được cư dân mạng phong tặng là cây cô đơn ở Lý Sơn. Cây có hình dáng lạ, đẹp được nhiều du khách ưu thích check-in. Ngoài cây cô đơn trên Đảo Bé còn có cây cầu sống ảo du khách không thể bỏ qua.',
      text4: 'Ở lại homestay tại Đảo Bé.',
      label11: 'So với các homestay trên Đảo Lớn thì hiện tại ở Đảo Bé có rất nhiều homestay giúp du khách có thể gần gũi với thiên nhiên. Buổi tối bạn có muốn tổ chức một buổi tiệc BBQ trên biển thật sự hay căm trại tại Đảo Bé. Đây sẽ là những trải nghiệm mà không phải ai cũng có thể có được khi đến Lý Sơn.',
      offer: [
        { img1: require('./../img/vinh71.png'), textimg1: 'Thắng cảnh Hòn Đụn', },
        { img1: require('./../img/vinh72.png'), textimg1: 'Núi Thới Lới', },
        { img1: require('./../img/vinh73.png'), textimg1: 'Phú Quốc, Kiên Giang', },
      ]
    },
    {
      id: 3,
      text: 'Đi du thuyền ra Vịnh Hạ Long',
      text1: 'QUảng Ninh, Việt Nam',
      img: 'https://scontent.fhph1-1.fna.fbcdn.net/v/t1.15752-9/116133106_3107313955984732_7173921754753671531_n.jpg?_nc_cat=100&ccb=1-3&_nc_sid=ae9488&_nc_ohc=WMhTPSewzMgAX_4gbCq&_nc_ht=scontent.fhph1-1.fna&oh=6a093c029e84b3c32211b22dba578077&oe=60A84779',
      price: '2.000.000',
      mapaddress: {
        latitude: 13.5232757,
        longitude: 108.1051243,
      },
      marker: {
        latitude: 13.118198,
        longitude: 108.852250,
      },
      introduce1: require('./../img/vinh68.png'),
      introduce2: require('./../img/vinh69.png'),
      introduce3: require('./../img/vinh70.png'),
      content1: 'Di chuyển từ Đảo lớn sang Đảo bé',
      label1: 'Để di chuyển từ Đảo Lớn sang Đảo Bé du khách sẽ di chuyển bằng Ca Nô. Mỗi lượt vé ca nô khứ hồi hiện nay dành cho du khách là 80k/du khách/khứ hồi.',
      label2: 'Bảng giá thuê ca nô nguyên chiếc khứ hồi:',
      label3: '- Ca nô 25 chỗ: 1600k',
      label4: '- Ca nô 35 chỗ: 2600k.',
      label5: '- Ca nô 40 chỗ: 3100k.',
      content2: 'Thời điểm thích hợp để khám phá Đảo Bé Lý Sơn.',
      label6: ' - Nếu đi Đảo Bé trong ngày, du khách nên xuất phát từ Đảo Lớn lúc sáng sau đó chiều về lại. Du khách ở lại Đảo Bé một ngày thì nên xuất phát từ sáng và về lại lúc trưa ngày hôm sau.',
      label7: ' - Nếu đi Đảo Bé trong ngày, du khách nên xuất phát từ Đảo Lớn lúc sáng sau đó chiều về lại. Du khách ở lại Đảo Bé một ngày thì nên xuất phát từ sáng và về lại lúc trưa ngày hôm sau.',
      content3: 'Chơi gì ở Đảo Bé?',
      text1: 'Lặn ngắm san hô.',
      label8: ' Rạn san hô ở Đảo Bé được đánh giá đẹp nhất Việt Nam. Du khách có thể lựa chọn thuê thuyền thúng đi lặn san hô. Mỗi lần lặn san hô như vậy là giá 80k/người. Giá lặn san hô đã bao gồm tiền thuê kính, thuê áo phao.',
      text2: 'Tắm biển ở Đảo Bé.',
      label9: 'Bãi Sau là bãi tắm nổi tiếng nhất tại Lý Sơn. Ở bãi tắm có nhiều bãi đá đen trầm tích để du khách có thể check-in với những tấm ảnh ấn tượng. Ở Bãi Sau sóng biển khá là bình yên nên việc tắm biển rất thích thú.',
      text3: 'Check-in cây cô đơn và cầu sống ảo.',
      label10: 'Cây phong ba dù đứng một mình ở Bãi Tây vẫn được cư dân mạng phong tặng là cây cô đơn ở Lý Sơn. Cây có hình dáng lạ, đẹp được nhiều du khách ưu thích check-in. Ngoài cây cô đơn trên Đảo Bé còn có cây cầu sống ảo du khách không thể bỏ qua.',
      text4: 'Ở lại homestay tại Đảo Bé.',
      label11: 'So với các homestay trên Đảo Lớn thì hiện tại ở Đảo Bé có rất nhiều homestay giúp du khách có thể gần gũi với thiên nhiên. Buổi tối bạn có muốn tổ chức một buổi tiệc BBQ trên biển thật sự hay căm trại tại Đảo Bé. Đây sẽ là những trải nghiệm mà không phải ai cũng có thể có được khi đến Lý Sơn.',
      offer: [
        { img1: require('./../img/vinh71.png'), textimg1: 'Thắng cảnh Hòn Đụn', },
        { img1: require('./../img/vinh72.png'), textimg1: 'Núi Thới Lới', },
        { img1: require('./../img/vinh73.png'), textimg1: 'Phú Quốc, Kiên Giang', },
      ]
    },
  ],
};

export default function Experience(state = initialState, action) {
  switch (action.type) {
    default:
      return state;
  }
}